language: c

os:
  - linux
  - osx

compiler: 
   - gcc

sudo: required

before_script:
  - chmod +x ./travis_setup.sh
  - ./travis_setup.sh
  - export CC=mpicc
  - export CXX=mpicxx

script:
  - ( ./configure && make )
