language: c

os:
  - linux
  - osx

compiler: 
   - gcc

sudo: required

before_script:
  - ./travis_setup.sh

  - export OMPI_CC=gcc-4.8
  - export OMPI_CXX=g++-4.8

script:
  - ( ./configure && make )
